# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
     #{id: 16, size: 0.05, name: Tag16},
     {id: 5, size: 0.05, name: Tag5},
     {id: 7, size: 0.05, name: Tag7},
     #{id: 11, size: 0.05, name: Tag11},
     #{id: 3, size: 0.05, name: Tag3},
     {id: 9, size: 0.05, name: Tag9},
     {id: 2, size: 0.05, name: Tag2},
     #{id: 19, size: 0.05, name: Tag19},		
     #{id: 22, size: 0.05, name: Tag22},
     {id: 12, size: 0.05, name: Tag12},
     #{id: 25, size: 0.05, name: Tag25},
     #{id: 24, size: 0.05, name: Tag24},
     #{id: 18, size: 0.05, name: Tag18},
     #{id: 17, size: 0.05, name: Tag17},
     {id: 13, size: 0.05, name: Tag13},
     #{id: 23, size: 0.05, name: Tag23},
     #{id: 36, size: 0.05, name: Tag36},
     #{id: 1, size: 0.05, name: Tag1},
     {id: 0, size: 0.05, name: Tag0}
     
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
  ]
